name: JHipster

on:
  push:
    branches:
    - release/*
  pull_request:
    types: [closed]
    branches:
    - release/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      run: |
        sudo curl -sL https://deb.nodesource.com/setup_16.x | bash -
        sudo apt-get install -y nodejs
    - name: Run JHipster command
      run: jhipster aws
